window.TAYYIBAT_WORKOUTS={
photoCredits:[
{file:'squat.jpg',by:'MART PRODUCTION',site:'Pexels',url:'https://www.pexels.com/photo/a-woman-doing-squats-at-home-8846119/'},
{file:'pushup.jpg',by:'Ron Lach',site:'Pexels',url:'https://www.pexels.com/photo/woman-exercising-at-home-7900682/'},
{file:'plank.jpg',by:'Margaret Young',site:'Unsplash',url:'https://unsplash.com/photos/mgC52hk8TeU'},
{file:'lunge.jpg',by:'Polina Tankilevitch',site:'Pexels',url:'https://www.pexels.com/photo/woman-watching-online-workout-video-6516232/'},
{file:'stretch.jpg',by:'Gustavo Fring',site:'Pexels',url:'https://www.pexels.com/photo/a-woman-in-active-wear-stretching-6496120/'},
{file:'chair.jpg',by:'Centre for Ageing Better',site:'Pexels',url:'https://www.pexels.com/photo/seniors-exercising-11674389/'}
],
exercises:[
{id:'march',ar:'المشي في المكان',en:'March in place',photo:'chair.jpg',credit:'Centre for Ageing Better / Pexels',area:'cardio',level:'beginner',equipment:'none',mode:'time',seconds:60,sets:3,rest:25,met:3.5,easier:'seated-march',harder:'high-knees',cueAr:'قف طويلًا، حرّك الذراعين وارفع الركبتين بالتبادل بوتيرة مريحة.',cueEn:'Stand tall, swing your arms, and alternate knee lifts at a comfortable pace.',errorsAr:'الميل للخلف، حبس النفس، رفع السرعة قبل الإحماء.',errorsEn:'Leaning back, holding breath, rushing before warm-up.'},
{id:'seated-march',ar:'مشي جلوس على الكرسي',en:'Seated march',photo:'chair.jpg',credit:'Centre for Ageing Better / Pexels',area:'cardio',level:'beginner',equipment:'chair',mode:'time',seconds:60,sets:2,rest:25,met:2.5,easier:null,harder:'march',cueAr:'اجلس على كرسي ثابت وارفع الركبتين بالتبادل مع ظهر مستقيم.',cueEn:'Sit on a stable chair and alternate knee lifts with a tall posture.',errorsAr:'الانحناء للأمام أو استخدام كرسي متحرك.',errorsEn:'Slouching forward or using an unstable chair.'},
{id:'high-knees',ar:'رفع الركبتين',en:'High knees',photo:'squat.jpg',credit:'MART PRODUCTION / Pexels',area:'cardio',level:'intermediate',equipment:'none',mode:'time',seconds:35,sets:3,rest:35,met:7.5,easier:'march',harder:null,cueAr:'ارفع الركبتين بسرعة متحكم بها مع بقاء الجذع مستقيمًا.',cueEn:'Drive knees up at a controlled fast pace while staying tall.',errorsAr:'القفز العنيف أو فقدان التحكم بالهبوط.',errorsEn:'Hard pounding or losing landing control.'},
{id:'chair-squat',ar:'جلوس وقيام من الكرسي',en:'Chair sit-to-stand',photo:'chair.jpg',credit:'Centre for Ageing Better / Pexels',area:'legs',level:'beginner',equipment:'chair',mode:'reps',reps:10,sets:3,rest:45,met:4,easier:'seated-march',harder:'squat',cueAr:'المس الكرسي بخفة ثم قف بالضغط عبر القدمين.',cueEn:'Touch the chair lightly, then stand by driving through your feet.',errorsAr:'السقوط على الكرسي أو انهيار الركبتين للداخل.',errorsEn:'Dropping onto the chair or knees collapsing inward.'},
{id:'squat',ar:'سكوات وزن الجسم',en:'Bodyweight squat',photo:'squat.jpg',credit:'MART PRODUCTION / Pexels',area:'legs',level:'intermediate',equipment:'none',mode:'reps',reps:12,sets:3,rest:45,met:5,easier:'chair-squat',harder:'pulse-squat',cueAr:'ادفع الورك للخلف، اجعل الركبتين باتجاه أصابع القدم والصدر مرفوعًا.',cueEn:'Sit hips back, track knees over toes, and keep your chest tall.',errorsAr:'تقريب الركبتين للداخل، رفع الكعبين، تقويس الظهر.',errorsEn:'Knees caving in, heels lifting, rounding the back.'},
{id:'pulse-squat',ar:'سكوات نبضي',en:'Pulse squat',photo:'squat.jpg',credit:'MART PRODUCTION / Pexels',area:'legs',level:'advanced',equipment:'none',mode:'reps',reps:15,sets:3,rest:50,met:6,easier:'squat',harder:null,cueAr:'ابق في النصف السفلي وتحرك مسافة قصيرة مع تحكم.',cueEn:'Stay in the lower half and pulse through a small controlled range.',errorsAr:'الهبوط لعمق مؤلم أو فقد وضع الركبة.',errorsEn:'Dropping into painful depth or losing knee alignment.'},
{id:'reverse-lunge',ar:'لانج خلفي',en:'Reverse lunge',photo:'lunge.jpg',credit:'Polina Tankilevitch / Pexels',area:'legs',level:'intermediate',equipment:'none',mode:'reps',reps:8,sets:3,rest:45,met:5,easier:'assisted-lunge',harder:'split-squat',cueAr:'خذ خطوة للخلف وانزل بشكل عمودي ثم ادفع من القدم الأمامية.',cueEn:'Step back, lower vertically, then drive through the front foot.',errorsAr:'الاندفاع للأمام أو تضييق قاعدة القدمين.',errorsEn:'Lunging forward or using too narrow a stance.'},
{id:'assisted-lunge',ar:'لانج بمساعدة كرسي',en:'Assisted lunge',photo:'lunge.jpg',credit:'Polina Tankilevitch / Pexels',area:'legs',level:'beginner',equipment:'chair',mode:'reps',reps:8,sets:2,rest:45,met:4,easier:'chair-squat',harder:'reverse-lunge',cueAr:'استند بيد خفيفة على كرسي ثابت وخذ خطوة للخلف.',cueEn:'Use light support from a stable chair and step back under control.',errorsAr:'الاعتماد الكامل على الذراع أو كرسي غير ثابت.',errorsEn:'Pulling with the arm or using an unstable chair.'},
{id:'split-squat',ar:'سبليت سكوات',en:'Split squat',photo:'lunge.jpg',credit:'Polina Tankilevitch / Pexels',area:'legs',level:'advanced',equipment:'none',mode:'reps',reps:10,sets:3,rest:50,met:6,easier:'reverse-lunge',harder:null,cueAr:'ثبت القدمين وانزل عموديًا دون حركة للأمام والخلف.',cueEn:'Keep feet planted and move straight down and up.',errorsAr:'قاعدة ضيقة جدًا أو دفع الركبة للأمام بعنف.',errorsEn:'Too narrow a stance or aggressively driving the knee forward.'},
{id:'calf-raise',ar:'رفع السمانة',en:'Calf raise',photo:'squat.jpg',credit:'MART PRODUCTION / Pexels',area:'legs',level:'beginner',equipment:'none',mode:'reps',reps:15,sets:3,rest:30,met:3.5,easier:null,harder:null,cueAr:'ارفع الكعبين ببطء وانزل بتحكم، استند للحائط عند الحاجة.',cueEn:'Rise onto your toes slowly and lower with control; use a wall if needed.',errorsAr:'الاهتزاز السريع أو فقدان التوازن.',errorsEn:'Bouncing quickly or losing balance.'},
{id:'glute-bridge',ar:'جسر الأرداف',en:'Glute bridge',photo:'plank.jpg',credit:'Margaret Young / Unsplash (representative floor exercise photo)',area:'legs',level:'beginner',equipment:'mat',mode:'reps',reps:12,sets:3,rest:35,met:3.8,easier:null,harder:'single-bridge',cueAr:'اضغط بالكعبين وارفع الحوض حتى يصبح الجذع في خط مريح دون تقويس زائد.',cueEn:'Drive through heels and lift hips to a comfortable line without over-arching.',errorsAr:'الدفع بأسفل الظهر بدل الأرداف أو رفع الذقن.',errorsEn:'Overusing the lower back or lifting the chin.'},
{id:'single-bridge',ar:'جسر أرداف رجل واحدة',en:'Single-leg bridge',photo:'plank.jpg',credit:'Margaret Young / Unsplash (representative floor exercise photo)',area:'legs',level:'advanced',equipment:'mat',mode:'reps',reps:8,sets:3,rest:45,met:5,easier:'glute-bridge',harder:null,cueAr:'ثبت الحوض وادفع من كعب الرجل العاملة دون دوران.',cueEn:'Keep hips level and drive through the working heel without rotation.',errorsAr:'ميل الحوض أو شد الرقبة.',errorsEn:'Hip rotation or neck tension.'},
{id:'wall-pushup',ar:'ضغط على الحائط',en:'Wall push-up',photo:'pushup.jpg',credit:'Ron Lach / Pexels',area:'upper',level:'beginner',equipment:'wall',mode:'reps',reps:10,sets:3,rest:35,met:3.5,easier:null,harder:'incline-pushup',cueAr:'اجعل الجسم خطًا واحدًا واقترب بالصدر من الحائط ثم ادفع.',cueEn:'Keep a straight body line, bring chest toward the wall, then press away.',errorsAr:'ثني الورك أو رفع الكتفين للأذن.',errorsEn:'Bending at the hips or shrugging shoulders.'},
{id:'incline-pushup',ar:'ضغط مائل',en:'Incline push-up',photo:'pushup.jpg',credit:'Ron Lach / Pexels',area:'upper',level:'intermediate',equipment:'chair',mode:'reps',reps:10,sets:3,rest:40,met:5,easier:'wall-pushup',harder:'pushup',cueAr:'استخدم سطحًا ثابتًا وحافظ على خط واحد من الرأس للكعبين.',cueEn:'Use a stable surface and keep a straight line from head to heels.',errorsAr:'سطح متحرك أو سقوط الحوض.',errorsEn:'Unstable surface or sagging hips.'},
{id:'pushup',ar:'ضغط أرضي',en:'Push-up',photo:'pushup.jpg',credit:'Ron Lach / Pexels',area:'upper',level:'advanced',equipment:'mat',mode:'reps',reps:8,sets:3,rest:50,met:8,easier:'incline-pushup',harder:null,cueAr:'شد البطن، انزل الصدر بين اليدين ثم ادفع الأرض.',cueEn:'Brace your core, lower chest between hands, then press the floor away.',errorsAr:'فتح المرفقين بزاوية كبيرة أو سقوط الحوض.',errorsEn:'Elbows flaring too wide or hips sagging.'},
{id:'wall-shoulder-tap',ar:'لمس الكتف على الحائط',en:'Wall shoulder tap',photo:'pushup.jpg',credit:'Ron Lach / Pexels',area:'upper',level:'beginner',equipment:'wall',mode:'reps',reps:12,sets:3,rest:30,met:3.2,easier:null,harder:'plank-tap',cueAr:'ميل خفيف على الحائط والمس الكتف المقابل بالتبادل دون دوران الجذع.',cueEn:'Lean lightly into the wall and alternate shoulder taps without torso rotation.',errorsAr:'التمايل الكبير أو ألم الرسغ.',errorsEn:'Large side-to-side sway or wrist pain.'},
{id:'plank',ar:'بلانك',en:'Plank',photo:'plank.jpg',credit:'Margaret Young / Unsplash',area:'core',level:'intermediate',equipment:'mat',mode:'time',seconds:30,sets:3,rest:40,met:4,easier:'knee-plank',harder:'plank-tap',cueAr:'شد البطن والأرداف وحافظ على الرقبة محايدة.',cueEn:'Brace core and glutes and keep your neck neutral.',errorsAr:'هبوط الحوض أو حبس النفس.',errorsEn:'Sagging hips or holding breath.'},
{id:'knee-plank',ar:'بلانك على الركبتين',en:'Knee plank',photo:'plank.jpg',credit:'Margaret Young / Unsplash',area:'core',level:'beginner',equipment:'mat',mode:'time',seconds:20,sets:3,rest:35,met:3.3,easier:null,harder:'plank',cueAr:'حافظ على خط مستقيم من الرأس للركبتين وشد البطن.',cueEn:'Keep a straight line from head to knees and brace your core.',errorsAr:'تقويس أسفل الظهر أو تحميل الكتف الزائد.',errorsEn:'Arching lower back or overloading shoulders.'},
{id:'plank-tap',ar:'بلانك مع لمس الكتف',en:'Plank shoulder tap',photo:'plank.jpg',credit:'Margaret Young / Unsplash',area:'core',level:'advanced',equipment:'mat',mode:'reps',reps:10,sets:3,rest:45,met:5.5,easier:'plank',harder:null,cueAr:'وسع قاعدة القدمين قليلًا والمس الكتف المقابل مع تثبيت الحوض.',cueEn:'Use a slightly wider stance and tap the opposite shoulder while keeping hips still.',errorsAr:'دوران الحوض أو السرعة الزائدة.',errorsEn:'Hip rotation or rushing.'},
{id:'bird-dog',ar:'بيرد دوج',en:'Bird dog',photo:'stretch.jpg',credit:'Gustavo Fring / Pexels (representative mobility photo)',area:'core',level:'beginner',equipment:'mat',mode:'reps',reps:8,sets:3,rest:30,met:3,easier:null,harder:null,cueAr:'مد الذراع والرجل المتعاكسين مع ثبات الحوض.',cueEn:'Extend opposite arm and leg while keeping hips steady.',errorsAr:'فتح الحوض أو رفع الطرف أعلى من اللازم.',errorsEn:'Opening the hips or lifting limbs too high.'},
{id:'dead-bug',ar:'ديد باج',en:'Dead bug',photo:'stretch.jpg',credit:'Gustavo Fring / Pexels (representative mobility photo)',area:'core',level:'beginner',equipment:'mat',mode:'reps',reps:8,sets:3,rest:30,met:3,easier:null,harder:null,cueAr:'ثبت الجذع وحرّك الأطراف ببطء بالتبادل.',cueEn:'Keep your trunk controlled and alternate limbs slowly.',errorsAr:'تقوس الظهر أو الحركة بسرعة.',errorsEn:'Back arching or moving too fast.'},
{id:'side-bend',ar:'ميل جانبي واقف',en:'Standing side bend',photo:'stretch.jpg',credit:'Gustavo Fring / Pexels',area:'mobility',level:'beginner',equipment:'none',mode:'time',seconds:40,sets:2,rest:20,met:2.5,easier:null,harder:null,cueAr:'مد الذراع فوق الرأس ومل للجانب ضمن مدى مريح.',cueEn:'Reach overhead and lean to the side through a comfortable range.',errorsAr:'الالتواء للأمام أو الضغط على أسفل الظهر.',errorsEn:'Rotating forward or compressing the lower back.'},
{id:'mobility-flow',ar:'مرونة للجسم كامل',en:'Full-body mobility flow',photo:'stretch.jpg',credit:'Gustavo Fring / Pexels',area:'mobility',level:'beginner',equipment:'none',mode:'time',seconds:120,sets:1,rest:20,met:2.5,easier:null,harder:null,cueAr:'حركات بطيئة للكتفين والورك والكاحل ضمن مدى مريح.',cueEn:'Move shoulders, hips and ankles slowly through a comfortable range.',errorsAr:'إجبار المفاصل على مدى مؤلم.',errorsEn:'Forcing joints into a painful range.'},
{id:'step-jack',ar:'ستيب جاك بدون قفز',en:'Low-impact step jack',photo:'squat.jpg',credit:'MART PRODUCTION / Pexels (representative standing exercise photo)',area:'cardio',level:'beginner',equipment:'none',mode:'time',seconds:45,sets:3,rest:25,met:4.5,easier:'march',harder:'high-knees',cueAr:'خطوة جانبية مع رفع الذراعين بالتبادل بدون قفز.',cueEn:'Step side to side while raising arms, with no jumping.',errorsAr:'خطوات أكبر من قدرتك على التوازن.',errorsEn:'Steps wider than your balance can control.'},
{id:'shadow-box',ar:'ملاكمة هوائية',en:'Shadow boxing',photo:'squat.jpg',credit:'MART PRODUCTION / Pexels (representative standing workout photo)',area:'cardio',level:'intermediate',equipment:'none',mode:'time',seconds:45,sets:4,rest:25,met:6,easier:'march',harder:null,cueAr:'حافظ على الذقن منخفضة واضرب للأمام مع دوران خفيف للجذع.',cueEn:'Keep chin tucked and punch forward with gentle torso rotation.',errorsAr:'قفل المرفق أو دوران الركبة بعنف.',errorsEn:'Locking elbows or twisting knees aggressively.'}
],
programs:[
{id:'starter10',ar:'بداية 10 دقائق',en:'10-min starter',level:'beginner',items:['march','chair-squat','wall-pushup','bird-dog','side-bend']},
{id:'no-jump15',ar:'حرق بدون قفز 15 دقيقة',en:'15-min no-jump burn',level:'beginner',items:['march','step-jack','chair-squat','wall-pushup','calf-raise','side-bend']},
{id:'full20',ar:'جسم كامل 20 دقيقة',en:'20-min full body',level:'intermediate',items:['march','squat','reverse-lunge','incline-pushup','glute-bridge','plank','side-bend']},
{id:'core15',ar:'بطن ووسط 15 دقيقة',en:'15-min core',level:'beginner',items:['march','bird-dog','dead-bug','knee-plank','glute-bridge','side-bend']},
{id:'upper15',ar:'جزء علوي 15 دقيقة',en:'15-min upper body',level:'intermediate',items:['march','wall-shoulder-tap','incline-pushup','plank','shadow-box','side-bend']},
{id:'legs15',ar:'أرجل 15 دقيقة',en:'15-min legs',level:'intermediate',items:['march','squat','reverse-lunge','calf-raise','glute-bridge','side-bend']},
{id:'mobility10',ar:'مرونة 10 دقائق',en:'10-min mobility',level:'beginner',items:['seated-march','side-bend','mobility-flow','bird-dog']},
{id:'strong25',ar:'قوة منزلية 25 دقيقة',en:'25-min home strength',level:'advanced',items:['high-knees','pulse-squat','split-squat','pushup','single-bridge','plank-tap','mobility-flow']}
],
plans:{
7:['starter10','mobility10','no-jump15','rest','full20','core15','mobility10'],
14:['starter10','mobility10','no-jump15','rest','legs15','upper15','mobility10','full20','rest','core15','no-jump15','legs15','upper15','mobility10'],
30:['starter10','mobility10','no-jump15','rest','legs15','upper15','mobility10','full20','rest','core15','no-jump15','legs15','upper15','mobility10','full20','rest','strong25','mobility10','core15','no-jump15','legs15','upper15','rest','full20','mobility10','strong25','core15','rest','no-jump15','mobility10']
}
};